version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: minimedium-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: minimedium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - minimedium_postgres_data:/var/lib/postgresql/data

volumes:
  minimedium_postgres_data:
